-------------------------------------------------------------------------------
Test set: ua.tqs.ReCollect.StepDefinitionsRegisterTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 10.913 s <<< FAILURE! - in ua.tqs.ReCollect.StepDefinitionsRegisterTest
a_user_submits_credentials_that_don_t_exist_in_the_DB  Time elapsed: 0.457 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <200 OK> but was: <500 INTERNAL_SERVER_ERROR>
	at ua.tqs.ReCollect.StepDefinitionsRegisterTest.a_user_submits_credentials_that_don_t_exist_in_the_DB(StepDefinitionsRegisterTest.java:84)

a_new_user_should_be_created_with_the_inserted_credentials  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NullPointerException
	at ua.tqs.ReCollect.StepDefinitionsRegisterTest.a_new_user_should_be_created_with_the_inserted_credentials(StepDefinitionsRegisterTest.java:96)

